### ISSUE TITLE
Ruff GitHub Action unable to access `lincbrain/linc-convert`

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-convert#30]
Hi @calvinchai, I am receiving the error below with the Ruff Github Actions workflow and am not sure how to resolve it.  See [latest run](https://github.com/lincbrain/linc-convert/actions/runs/11977944485/job/33396932181#step:5:44).

```
remote: Permission to lincbrain/linc-convert.git denied to github-actions[bot].
```
Thanks.

**Comment by calvinchai** [comment]
I saw this error on all PRs. I am looking at it.

**Comment by calvinchai** [comment]
@kabilar Could you please check if you have github action enabled on your fork?

**Comment by kabilar** [comment]
Hi @calvinchai, yes, I do but the GitHub Actions workflows are only enabled for `on: pull_request`.

I just re-triggered the CI checks for #23 and it looks to have worked.  Thank you.
